global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertas@seudominio.com'
  smtp_auth_username: 'alertas@seudominio.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'urgent-notifications'
      continue: true

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'suporte@seudominio.com'
        send_resolved: true
        headers:
          subject: 'Alerta: {{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'

  - name: 'urgent-notifications'
    email_configs:
      - to: 'emergencia@seudominio.com'
        send_resolved: true
        headers:
          subject: 'URGENTE: {{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'
    webhook_configs:
      - url: 'https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage'
        send_resolved: true
        message: '🚨 ALERTA CRÍTICO: {{ template "telegram.default.message" . }}'

templates:
  - '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 