groups:
  - name: node
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de CPU"
          description: "CPU está acima de 80% por 5 minutos"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de memória"
          description: "Memória está acima de 85% por 5 minutos"

      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de disco"
          description: "Disco está acima de 85% por 5 minutos"

  - name: application
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Alta taxa de erros"
          description: "Taxa de erros HTTP 5xx está acima de 5% por 5 minutos"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta latência"
          description: "95º percentil da latência está acima de 1 segundo por 5 minutos"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Serviço indisponível"
          description: "{{ $labels.job }} está indisponível"

  - name: database
    rules:
      - alert: HighDatabaseConnections
        expr: pg_stat_activity_count > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Muitas conexões no banco"
          description: "Número de conexões ativas está acima de 100 por 5 minutos"

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname="ai_startup_creator"}[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Queries lentas"
          description: "Existem queries executando por mais de 5 minutos" 